### PR TITLE
chore: add snapshots to error details

### PR DESCRIPTION
**Pull request by alexruzenhack**
### Acceptance Criteria
- Add inline snpatshot to validation error details in push register, update and unregister tests

### Security Checklist
- [ ] Make sure you do not include new dependencies in the project unless strictly necessary and do not include dev-dependencies as production ones. More dependencies increase the possibility of one of them being hijacked and affecting us.

### CODE REVIEW

**Review by tuliomir — APPROVED** [review]
I like the additional validations, but wouldn't they be easier to read/maintain if we used something like `expect().toStrictlyEqual()` and passed the object in plain javascript instead of serialized? Ex.:

```js
expect(returnBody.details).toStrictlyEqual([
  {
    message: '"pushProvider" with value (...)',
    path: [ 'pushProvider' ],
  }
]);
```

**Comment by alexruzenhack** [comment]
> I like the additional validations, but wouldn't they be easier to read/maintain if we used something like expect().toStrictlyEqual() and passed the object in plain javascript instead of serialized?

More readable yes, but not easier to maintain. The inline snapshot is a great tool to maintain a check over data that have more potential to change. To update it we jest need to run jest with `-u` flag.

**Review by andreabadesso — APPROVED** [review]
Didn't know about `toMatchInlineSnapshot`, nice!

We could refactor this in many other test files, can you open an issue to do that later?

**Comment by alexruzenhack** [comment]
> Didn't know about `toMatchInlineSnapshot`, nice!
> 
> We could refactor this in many other test files, can you open an issue to do that later?

Sure, here it is: https://github.com/HathorNetwork/hathor-wallet-service/issues/330

**Pull request merged**
